# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: CASIA-B
  dataset_root: /root/autodl-tmp/CASIA-B
  dataset_partition: /root/autodl-tmp/CASIA-B/CASIA-B.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B
  eps: 0.8
  min_samples: 4

evaluator_cfg:
  enable_float16: true 
  restore_ckpt_strict: false
  restore_hint: 210000
  save_name: GaitGL
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: ClusterTripletLoss
    log_prefix: triplet

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 74

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 210000
    - 210300
    - 210600
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  with_cluster: true
  cluster_iter: 300
  log_iter: 10
  restore_ckpt_strict: false
  optimizer_reset: true
  restore_hint: 210000
  save_iter: 100
  save_name: GaitGL
  sync_BN: true
  total_iter: 212100
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler

cluster_cfg:
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
    type: InferenceSampler

  transform:
    - type: BaseSilCuttingTransform
